export const housingData = {
  houses: [
    {
      id: 1,
      title: "Cozy Apartment in Downtown",
      type: "rent",
      price: 1500,
      sqft: 850,
      bedrooms: 2,
      bathrooms: 1,
      propertyType: "apartment",
      condition: "excellent",
      description:
        "A modern 2-bedroom apartment with city views, fully furnished and close to public transport.",
      location: "123 Main St, New York, NY 10001",
      contactEmail: "owner1@example.com",
      posted: "this week",
      images: [
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 2,
      title: "Spacious Family Home",
      type: "sale",
      price: 350000,
      sqft: 2200,
      bedrooms: 4,
      bathrooms: 2,
      propertyType: "house",
      condition: "excellent",
      description:
        "4-bedroom house with a large backyard, garage, and modern kitchen. Perfect for families.",
      location: "456 Elm St, Los Angeles, CA 90001",
      contactEmail: "owner2@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 3,
      title: "Luxury Condo by the Beach",
      type: "rent",
      price: 2500,
      sqft: 1400,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "condo",
      condition: "excellent",
      description:
        "Oceanfront condo with 3 bedrooms, balcony, and access to private beach and pool.",
      location: "789 Ocean Ave, Miami, FL 33101",
      contactEmail: "owner3@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 4,
      title: "Modern Loft in Arts District",
      type: "sale",
      price: 480000,
      sqft: 1100,
      bedrooms: 1,
      bathrooms: 1,
      propertyType: "loft",
      condition: "good",
      description:
        "Stylish 1-bedroom loft with high ceilings, exposed brick, and proximity to trendy cafes and galleries.",
      location: "321 Pine St, Seattle, WA 98101",
      contactEmail: "owner4@example.com",
      posted: "last month",
      images: [
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 5,
      title: "Suburban Bungalow",
      type: "rent",
      price: 1800,
      sqft: 1600,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "house",
      condition: "good",
      description:
        "Charming 3-bedroom bungalow with a spacious front porch and updated appliances.",
      location: "654 Oak St, Austin, TX 78701",
      contactEmail: "owner5@example.com",
      posted: "last three months",
      images: [
        "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 6,
      title: "Urban Studio Apartment",
      type: "sale",
      price: 220000,
      sqft: 650,
      bedrooms: 1,
      bathrooms: 1,
      propertyType: "studio",
      condition: "excellent",
      description:
        "Compact studio with modern finishes, ideal for young professionals, located near downtown.",
      location: "987 Cedar Ave, Chicago, IL 60601",
      contactEmail: "owner6@example.com",
      posted: "last six months",
      images: [
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
    },
    {
      id: 7,
      title: "Luxury Townhouse",
      type: "rent",
      price: 3200,
      sqft: 2800,
      bedrooms: 4,
      bathrooms: 3,
      propertyType: "townhouse",
      condition: "excellent",
      description:
        "Elegant 4-bedroom townhouse with rooftop terrace and smart home features.",
      location: "147 Maple Dr, Boston, MA 02108",
      contactEmail: "owner7@example.com",
      posted: "last year",
      images: [
        "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
    },
    {
      id: 8,
      title: "Beachfront Cottage",
      type: "sale",
      price: 750000,
      sqft: 1200,
      bedrooms: 2,
      bathrooms: 1,
      propertyType: "house",
      condition: "good",
      description:
        "Quaint 2-bedroom cottage with stunning ocean views and private beach access.",
      location: "258 Coastal Rd, San Diego, CA 92109",
      contactEmail: "owner8@example.com",
      posted: "this week",
      images: [
        "https://images.unsplash.com/photo-1560448205-4d9b3e6bb6db?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 9,
      title: "Rustic Farmhouse",
      type: "rent",
      price: 2000,
      sqft: 2100,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "farmhouse",
      condition: "needs-renovation",
      description:
        "Cozy 3-bedroom farmhouse with a large lot, barn, and modern upgrades.",
      location: "369 Rural Rd, Nashville, TN 37201",
      contactEmail: "owner9@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1605146769289-440113cc3d00?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
    },
    {
      id: 10,
      title: "Penthouse with Skyline Views",
      type: "sale",
      price: 1250000,
      sqft: 2000,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "penthouse",
      condition: "excellent",
      description:
        "Luxurious 3-bedroom penthouse with floor-to-ceiling windows and a private rooftop deck.",
      location: "741 Skyline Blvd, San Francisco, CA 94105",
      contactEmail: "owner10@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2053&q=80",
      ],
    },
    {
      id: 11,
      title: "Historic Townhome",
      type: "rent",
      price: 2800,
      sqft: 2400,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "townhouse",
      condition: "good",
      description:
        "Beautifully restored 3-bedroom townhome with original hardwood floors and modern amenities.",
      location: "852 Heritage St, Philadelphia, PA 19106",
      contactEmail: "owner11@example.com",
      posted: "last month",
      images: [
        "https://images.unsplash.com/photo-1605146769289-440113cc3d00?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=8",
      ],
    },
    {
      id: 12,
      title: "Downtown Condo",
      type: "sale",
      price: 450000,
      sqft: 1300,
      bedrooms: 2,
      bathrooms: 2,
      propertyType: "condo",
      condition: "excellent",
      description:
        "Sleek 2-bedroom condo with gym access, concierge service, and proximity to shopping.",
      location: "963 City Center, Denver, CO 80202",
      contactEmail: "owner12@example.com",
      posted: "last three months",
      images: [
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 13,
      title: "Elegant City Penthouse",
      type: "rent",
      price: 3500,
      sqft: 1900,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "penthouse",
      condition: "excellent",
      description:
        "Stunning 3-bedroom penthouse with panoramic city views and a private terrace.",
      location: "101 Sky Tower, Chicago, IL 60601",
      contactEmail: "owner13@example.com",
      posted: "last six months",
      images: [
        "https://images.unsplash.com/photo-1605146769289-440113cc3d00?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
    },
    {
      id: 14,
      title: "Riverside Villa",
      type: "sale",
      price: 890000,
      sqft: 3200,
      bedrooms: 5,
      bathrooms: 4,
      propertyType: "villa",
      condition: "excellent",
      description:
        "Luxurious 5-bedroom villa with river views, private dock, and modern design.",
      location: "234 River Rd, Portland, OR 97201",
      contactEmail: "owner14@example.com",
      posted: "last year",
      images: [
        "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2053&q=80",
      ],
    },
    {
      id: 15,
      title: "Cozy Mountain Cabin",
      type: "rent",
      price: 1200,
      sqft: 1000,
      bedrooms: 2,
      bathrooms: 1,
      propertyType: "cabin",
      condition: "good",
      description:
        "Charming 2-bedroom cabin with fireplace, perfect for a mountain getaway.",
      location: "567 Pine Trail, Aspen, CO 81611",
      contactEmail: "owner15@example.com",
      posted: "this week",
      images: [
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 16,
      title: "Modern Suburban House",
      type: "sale",
      price: 425000,
      sqft: 2300,
      bedrooms: 4,
      bathrooms: 3,
      propertyType: "house",
      condition: "excellent",
      description:
        "4-bedroom home with a large garden and updated kitchen in a quiet suburb.",
      location: "789 Oak Lane, Raleigh, NC 27601",
      contactEmail: "owner16@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 17,
      title: "Beachside Bungalow",
      type: "rent",
      price: 1800,
      sqft: 1400,
      bedrooms: 2,
      bathrooms: 1,
      propertyType: "house",
      condition: "good",
      description:
        "2-bedroom bungalow with direct beach access and ocean views.",
      location: "321 Sea Breeze Ave, Honolulu, HI 96801",
      contactEmail: "owner17@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 18,
      title: "Urban Loft Retreat",
      type: "sale",
      price: 380000,
      sqft: 950,
      bedrooms: 1,
      bathrooms: 1,
      propertyType: "loft",
      condition: "excellent",
      description:
        "Trendy 1-bedroom loft with open layout and city skyline views.",
      location: "654 Urban St, Austin, TX 78701",
      contactEmail: "owner18@example.com",
      posted: "last month",
      images: [
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 19,
      title: "Spacious Ranch House",
      type: "rent",
      price: 2200,
      sqft: 2600,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "ranch",
      condition: "good",
      description:
        "3-bedroom ranch with a large patio and scenic countryside views.",
      location: "987 Ranch Rd, Boise, ID 83701",
      contactEmail: "owner19@example.com",
      posted: "last three months",
      images: [
        "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 20,
      title: "Luxury Lakeside Cottage",
      type: "sale",
      price: 650000,
      sqft: 1700,
      bedrooms: 4,
      bathrooms: 2,
      propertyType: "cottage",
      condition: "excellent",
      description:
        "4-bedroom cottage with lake views, private dock, and modern amenities.",
      location: "147 Lake Shore Dr, Minneapolis, MN 55401",
      contactEmail: "owner20@example.com",
      posted: "last six months",
      images: [
        "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
    },
    {
      id: 21,
      title: "Classic Colonial Home",
      type: "rent",
      price: 3000,
      sqft: 2900,
      bedrooms: 5,
      bathrooms: 3,
      propertyType: "colonial",
      condition: "excellent",
      description: "5-bedroom colonial with historic charm and modern updates.",
      location: "258 Colonial Way, Charleston, SC 29401",
      contactEmail: "owner21@example.com",
      posted: "last year",
      images: [
        "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
    },
    {
      id: 22,
      title: "Downtown Studio",
      type: "sale",
      price: 280000,
      sqft: 700,
      bedrooms: 1,
      bathrooms: 1,
      propertyType: "studio",
      condition: "good",
      description:
        "Compact studio with modern design, ideal for singles or couples.",
      location: "369 City Plaza, Phoenix, AZ 85001",
      contactEmail: "owner22@example.com",
      posted: "this week",
      images: [
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 23,
      title: "Seaside Mansion",
      type: "rent",
      price: 5500,
      sqft: 4500,
      bedrooms: 6,
      bathrooms: 5,
      propertyType: "mansion",
      condition: "excellent",
      description:
        "Luxurious 6-bedroom mansion with oceanfront views and private pool.",
      location: "741 Oceanfront Dr, Malibu, CA 90265",
      contactEmail: "owner23@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 24,
      title: "Urban Townhouse",
      type: "sale",
      price: 520000,
      sqft: 1800,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "townhouse",
      condition: "excellent",
      description:
        "3-bedroom townhouse with rooftop deck in the heart of the city.",
      location: "852 Urban Ave, Atlanta, GA 30301",
      contactEmail: "owner24@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 25,
      title: "Country Estate",
      type: "rent",
      price: 4200,
      sqft: 5000,
      bedrooms: 7,
      bathrooms: 5,
      propertyType: "estate",
      condition: "excellent",
      description:
        "Grand 7-bedroom estate with expansive grounds and equestrian facilities.",
      location: "963 Country Lane, Lexington, KY 40501",
      contactEmail: "owner25@example.com",
      posted: "last month",
      images: [
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 26,
      title: "City View Apartment",
      type: "sale",
      price: 380000,
      sqft: 1050,
      bedrooms: 2,
      bathrooms: 2,
      propertyType: "apartment",
      condition: "excellent",
      description: "2-bedroom apartment with stunning city skyline views.",
      location: "147 Skyline Rd, Dallas, TX 75201",
      contactEmail: "owner26@example.com",
      posted: "last three months",
      images: [
        "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 27,
      title: "Riverside Condo",
      type: "rent",
      price: 1900,
      sqft: 1500,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "condo",
      condition: "good",
      description:
        "3-bedroom condo with riverfront access and modern interiors.",
      location: "258 Riverwalk, St. Louis, MO 63101",
      contactEmail: "owner27@example.com",
      posted: "last six months",
      images: [
        "https://images.unsplash.com/photo-1600585152915-18c7f8f4596e?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 28,
      title: "Mountain Retreat",
      type: "sale",
      price: 420000,
      sqft: 1300,
      bedrooms: 2,
      bathrooms: 1,
      propertyType: "cabin",
      condition: "good",
      description:
        "2-bedroom retreat with mountain views and a cozy fireplace.",
      location: "369 Summit Dr, Denver, CO 80202",
      contactEmail: "owner28@example.com",
      posted: "last year",
      images: [
        "https://images.unsplash.com/photo-1600585153490-7d16b7e91b7a?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 29,
      title: "Suburban Duplex",
      type: "rent",
      price: 1600,
      sqft: 2000,
      bedrooms: 4,
      bathrooms: 2,
      propertyType: "duplex",
      condition: "good",
      description: "4-bedroom duplex with separate units and a shared garden.",
      location: "741 Suburban St, Orlando, FL 32801",
      contactEmail: "owner29@example.com",
      posted: "this week",
      images: [
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 30,
      title: "Oceanfront Villa",
      type: "sale",
      price: 1200000,
      sqft: 3000,
      bedrooms: 5,
      bathrooms: 4,
      propertyType: "villa",
      condition: "excellent",
      description:
        "5-bedroom villa with private beach access and infinity pool.",
      location: "852 Ocean Dr, Santa Barbara, CA 93101",
      contactEmail: "owner30@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 31,
      title: "City Center Loft",
      type: "rent",
      price: 1700,
      sqft: 900,
      bedrooms: 1,
      bathrooms: 1,
      propertyType: "loft",
      condition: "excellent",
      description: "1-bedroom loft with high ceilings and urban convenience.",
      location: "963 Central Ave, Houston, TX 77001",
      contactEmail: "owner31@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 32,
      title: "Lakeside Chalet",
      type: "sale",
      price: 580000,
      sqft: 2500,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "chalet",
      condition: "excellent",
      description: "3-bedroom chalet with lake views and a private dock.",
      location: "147 Lakeview Rd, Seattle, WA 98101",
      contactEmail: "owner32@example.com",
      posted: "last month",
      images: [
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 33,
      title: "Historic Mansion",
      type: "rent",
      price: 4800,
      sqft: 4800,
      bedrooms: 6,
      bathrooms: 4,
      propertyType: "mansion",
      condition: "needs-renovation",
      description:
        "6-bedroom mansion with historic features and modern upgrades.",
      location: "258 Heritage Way, Savannah, GA 31401",
      contactEmail: "owner33@example.com",
      posted: "last three months",
      images: [
        "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 34,
      title: "Urban Penthouse",
      type: "sale",
      price: 950000,
      sqft: 2200,
      bedrooms: 4,
      bathrooms: 3,
      propertyType: "penthouse",
      condition: "excellent",
      description: "4-bedroom penthouse with city views and a private rooftop.",
      location: "369 Skyline Dr, Miami, FL 33101",
      contactEmail: "owner34@example.com",
      posted: "last six months",
      images: [
        "https://images.unsplash.com/photo-1605146769289-440113cc3d00?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
    },
    {
      id: 35,
      title: "Rustic Cabin",
      type: "rent",
      price: 1100,
      sqft: 800,
      bedrooms: 2,
      bathrooms: 1,
      propertyType: "cabin",
      condition: "good",
      description:
        "2-bedroom cabin with wood-burning fireplace and forest views.",
      location: "741 Forest Trail, Asheville, NC 28801",
      contactEmail: "owner35@example.com",
      posted: "last year",
      images: [
        "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
    },
    {
      id: 36,
      title: "Modern Townhome",
      type: "sale",
      price: 460000,
      sqft: 1900,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "townhouse",
      condition: "excellent",
      description: "3-bedroom townhome with smart home features and a garage.",
      location: "852 Modern St, Portland, OR 97201",
      contactEmail: "owner36@example.com",
      posted: "this week",
      images: [
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 37,
      title: "Beach Retreat",
      type: "rent",
      price: 2100,
      sqft: 1600,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "house",
      condition: "excellent",
      description:
        "3-bedroom retreat with direct beach access and ocean views.",
      location: "963 Beach Rd, Myrtle Beach, SC 29577",
      contactEmail: "owner37@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 38,
      title: "Suburban Cottage",
      type: "sale",
      price: 320000,
      sqft: 1400,
      bedrooms: 2,
      bathrooms: 1,
      propertyType: "cottage",
      condition: "good",
      description: "2-bedroom cottage with a garden and modern interiors.",
      location: "147 Cottage Ln, Sacramento, CA 95814",
      contactEmail: "owner38@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 39,
      title: "City Skyline Condo",
      type: "rent",
      price: 2300,
      sqft: 1200,
      bedrooms: 2,
      bathrooms: 2,
      propertyType: "condo",
      condition: "excellent",
      description: "2-bedroom condo with stunning city skyline views.",
      location: "258 Skyview Dr, Las Vegas, NV 89101",
      contactEmail: "owner39@example.com",
      posted: "last month",
      images: [
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 40,
      title: "Lakefront House",
      type: "sale",
      price: 720000,
      sqft: 2700,
      bedrooms: 4,
      bathrooms: 3,
      propertyType: "house",
      condition: "excellent",
      description: "4-bedroom house with lakefront access and a private pier.",
      location: "369 Lakefront Rd, Madison, WI 53701",
      contactEmail: "owner40@example.com",
      posted: "last three months",
      images: [
        "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 41,
      title: "Mountain Lodge",
      type: "rent",
      price: 1900,
      sqft: 1500,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "lodge",
      condition: "excellent",
      description: "3-bedroom lodge with mountain views and a hot tub.",
      location: "741 Summit Rd, Salt Lake City, UT 84101",
      contactEmail: "owner41@example.com",
      posted: "last six months",
      images: [
        "https://images.unsplash.com/photo-1600585154526-990dced4db0d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
    },
    {
      id: 42,
      title: "Urban Apartment",
      type: "sale",
      price: 290000,
      sqft: 850,
      bedrooms: 1,
      bathrooms: 1,
      propertyType: "apartment",
      condition: "good",
      description:
        "1-bedroom apartment with modern amenities in the city center.",
      location: "852 Urban Pl, San Antonio, TX 78201",
      contactEmail: "owner42@example.com",
      posted: "last year",
      images: [
        "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
    },
    {
      id: 43,
      title: "Riverside Townhouse",
      type: "rent",
      price: 2400,
      sqft: 2100,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "townhouse",
      condition: "excellent",
      description: "3-bedroom townhouse with river views and a private patio.",
      location: "963 Riverbank Rd, Pittsburgh, PA 15201",
      contactEmail: "owner43@example.com",
      posted: "this week",
      images: [
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 44,
      title: "Beachside Condo",
      type: "sale",
      price: 520000,
      sqft: 1300,
      bedrooms: 2,
      bathrooms: 2,
      propertyType: "condo",
      condition: "excellent",
      description: "2-bedroom condo with beach access and modern design.",
      location: "147 Seashell Dr, Virginia Beach, VA 23451",
      contactEmail: "owner44@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 45,
      title: "Country Manor",
      type: "rent",
      price: 3800,
      sqft: 4200,
      bedrooms: 6,
      bathrooms: 4,
      propertyType: "manor",
      condition: "excellent",
      description: "6-bedroom manor with expansive grounds and a barn.",
      location: "258 Country Rd, Louisville, KY 40201",
      contactEmail: "owner45@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 46,
      title: "City Duplex",
      type: "sale",
      price: 410000,
      sqft: 1100,
      bedrooms: 2,
      bathrooms: 2,
      propertyType: "duplex",
      condition: "good",
      description: "2-unit duplex with modern interiors in the city.",
      location: "369 Duplex St, Columbus, OH 43215",
      contactEmail: "owner46@example.com",
      posted: "last month",
      images: [
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 47,
      title: "Lakeside Retreat",
      type: "rent",
      price: 2700,
      sqft: 2400,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "house",
      condition: "excellent",
      description: "3-bedroom retreat with lake views and a private dock.",
      location: "741 Lakeview Ln, Milwaukee, WI 53201",
      contactEmail: "owner47@example.com",
      posted: "last three months",
      images: [
        "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 48,
      title: "Mountain Chalet",
      type: "sale",
      price: 480000,
      sqft: 1200,
      bedrooms: 2,
      bathrooms: 1,
      propertyType: "chalet",
      condition: "good",
      description: "2-bedroom chalet with mountain views and a fireplace.",
      location: "852 Alpine Rd, Vail, CO 81657",
      contactEmail: "owner48@example.com",
      posted: "last six months",
      images: [
        "https://images.unsplash.com/photo-1605146769289-440113cc3d00?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
    },
    {
      id: 49,
      title: "Suburban Villa",
      type: "rent",
      price: 2900,
      sqft: 2000,
      bedrooms: 4,
      bathrooms: 3,
      propertyType: "villa",
      condition: "excellent",
      description: "4-bedroom villa with a garden and modern kitchen.",
      location: "963 Villa Rd, Tampa, FL 33601",
      contactEmail: "owner49@example.com",
      posted: "last year",
      images: [
        "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
    },
    {
      id: 50,
      title: "Oceanview Apartment",
      type: "sale",
      price: 680000,
      sqft: 1600,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "apartment",
      condition: "excellent",
      description: "3-bedroom apartment with ocean views and a balcony.",
      location: "147 Oceanfront Pl, San Diego, CA 92109",
      contactEmail: "owner50@example.com",
      posted: "this week",
      images: [
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 51,
      title: "Modern Downtown Loft",
      type: "rent",
      price: 2100,
      sqft: 1100,
      bedrooms: 1,
      bathrooms: 1,
      propertyType: "loft",
      condition: "excellent",
      description:
        "Contemporary loft with industrial design and downtown location.",
      location: "789 Urban Ave, Charlotte, NC 28202",
      contactEmail: "owner51@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 52,
      title: "Garden View Cottage",
      type: "sale",
      price: 340000,
      sqft: 1400,
      bedrooms: 2,
      bathrooms: 1,
      propertyType: "cottage",
      condition: "good",
      description:
        "Charming cottage with beautiful garden views and updated kitchen.",
      location: "456 Garden St, Portland, ME 04101",
      contactEmail: "owner52@example.com",
      posted: "last month",
      images: [
        "https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=2065&auto=format&fit=crop",
      ],
    },
    {
      id: 53,
      title: "Executive Penthouse Suite",
      type: "rent",
      price: 4500,
      sqft: 2400,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "penthouse",
      condition: "excellent",
      description:
        "Luxurious penthouse with executive finishes and panoramic city views.",
      location: "123 Corporate Blvd, Dallas, TX 75201",
      contactEmail: "owner53@example.com",
      posted: "last three months",
      images: [
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 54,
      title: "Family Ranch Home",
      type: "sale",
      price: 580000,
      sqft: 2800,
      bedrooms: 4,
      bathrooms: 3,
      propertyType: "ranch",
      condition: "excellent",
      description:
        "Spacious ranch home perfect for families with large backyard and pool.",
      location: "789 Ranch Rd, Phoenix, AZ 85001",
      contactEmail: "owner54@example.com",
      posted: "last six months",
      images: [
        "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 55,
      title: "Urban Studio Efficiency",
      type: "rent",
      price: 1200,
      sqft: 600,
      bedrooms: 1,
      bathrooms: 1,
      propertyType: "studio",
      condition: "good",
      description:
        "Efficient studio apartment in the heart of the city, perfect for students.",
      location: "321 College Ave, Boston, MA 02108",
      contactEmail: "owner55@example.com",
      posted: "last year",
      images: [
        "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 56,
      title: "Luxury Waterfront Condo",
      type: "sale",
      price: 920000,
      sqft: 1800,
      bedrooms: 2,
      bathrooms: 2,
      propertyType: "condo",
      condition: "excellent",
      description:
        "Stunning waterfront condo with premium finishes and boat dock access.",
      location: "654 Harbor Dr, Miami, FL 33101",
      contactEmail: "owner56@example.com",
      posted: "this week",
      images: [
        "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?q=80&w=2065&auto=format&fit=crop",
      ],
    },
    {
      id: 57,
      title: "Mountain View Cabin",
      type: "rent",
      price: 1400,
      sqft: 900,
      bedrooms: 2,
      bathrooms: 1,
      propertyType: "cabin",
      condition: "good",
      description:
        "Cozy cabin with breathtaking mountain views and hiking trail access.",
      location: "987 Mountain Trail, Denver, CO 80202",
      contactEmail: "owner57@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=2071&auto=format&fit=crop",
      ],
    },
    {
      id: 58,
      title: "Historic Brownstone",
      type: "sale",
      price: 1100000,
      sqft: 3200,
      bedrooms: 5,
      bathrooms: 3,
      propertyType: "brownstone",
      condition: "needs-renovation",
      description:
        "Classic brownstone with historic charm and potential for modernization.",
      location: "123 Historic Ave, Brooklyn, NY 11201",
      contactEmail: "owner58@example.com",
      posted: "last month",
      images: [
        "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?q=80&w=2065&auto=format&fit=crop",
      ],
    },
    {
      id: 59,
      title: "Modern Eco Home",
      type: "rent",
      price: 2600,
      sqft: 1900,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "house",
      condition: "excellent",
      description:
        "Energy-efficient home with solar panels and sustainable materials.",
      location: "456 Green St, Seattle, WA 98101",
      contactEmail: "owner59@example.com",
      posted: "last three months",
      images: [
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=2074&auto=format&fit=crop",
      ],
    },
    {
      id: 60,
      title: "Downtown Luxury Apartment",
      type: "sale",
      price: 750000,
      sqft: 1500,
      bedrooms: 2,
      bathrooms: 2,
      propertyType: "apartment",
      condition: "excellent",
      description:
        "Premium downtown apartment with concierge and luxury amenities.",
      location: "789 Luxury Ln, Chicago, IL 60601",
      contactEmail: "owner60@example.com",
      posted: "last six months",
      images: [
        "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
    },
    {
      id: 61,
      title: "Secluded Forest Retreat",
      type: "rent",
      price: 1300,
      sqft: 1100,
      bedrooms: 2,
      bathrooms: 1,
      propertyType: "cabin",
      condition: "good",
      description:
        "Private retreat surrounded by forest, perfect for nature lovers.",
      location: "321 Forest Rd, Burlington, VT 05401",
      contactEmail: "owner61@example.com",
      posted: "last year",
      images: [
        "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 62,
      title: "Urban Garden Home",
      type: "sale",
      price: 620000,
      sqft: 1700,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "house",
      condition: "excellent",
      description:
        "City home with beautiful garden, perfect for urban gardening enthusiasts.",
      location: "654 Garden Ave, Austin, TX 78701",
      contactEmail: "owner62@example.com",
      posted: "this week",
      images: [
        "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2075&q=80",
      ],
    },
    {
      id: 63,
      title: "Executive Townhouse",
      type: "rent",
      price: 3200,
      sqft: 2100,
      bedrooms: 3,
      bathrooms: 2,
      propertyType: "townhouse",
      condition: "excellent",
      description:
        "Executive-style townhouse with premium finishes and garage parking.",
      location: "987 Executive Dr, Washington, DC 20001",
      contactEmail: "owner63@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?q=80&w=2065&auto=format&fit=crop",
      ],
    },
    {
      id: 64,
      title: "Vintage Craftsman Home",
      type: "sale",
      price: 780000,
      sqft: 2200,
      bedrooms: 4,
      bathrooms: 2,
      propertyType: "craftsman",
      condition: "good",
      description:
        "Beautiful craftsman home with original details and modern updates.",
      location: "123 Vintage St, Pasadena, CA 91101",
      contactEmail: "owner64@example.com",
      posted: "last month",
      images: [
        "https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=2065&auto=format&fit=crop",
      ],
    },
    {
      id: 65,
      title: "Modern Micro Apartment",
      type: "rent",
      price: 950,
      sqft: 400,
      bedrooms: 1,
      bathrooms: 1,
      propertyType: "studio",
      condition: "excellent",
      description:
        "Smart-designed micro apartment with efficient use of space.",
      location: "456 Micro St, San Francisco, CA 94102",
      contactEmail: "owner65@example.com",
      posted: "last three months",
      images: [
        "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 66,
      title: "Lakeside Family Home",
      type: "sale",
      price: 850000,
      sqft: 2600,
      bedrooms: 4,
      bathrooms: 3,
      propertyType: "house",
      condition: "excellent",
      description:
        "Perfect family home on the lake with dock and swimming area.",
      location: "789 Lakeview Dr, Madison, WI 53701",
      contactEmail: "owner66@example.com",
      posted: "last six months",
      images: [
        "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?q=80&w=2065&auto=format&fit=crop",
      ],
    },
    {
      id: 67,
      title: "Downtown Artist Loft",
      type: "rent",
      price: 1800,
      sqft: 1300,
      bedrooms: 1,
      bathrooms: 1,
      propertyType: "loft",
      condition: "good",
      description:
        "Spacious artist loft with north light and creative atmosphere.",
      location: "321 Arts District, Detroit, MI 48201",
      contactEmail: "owner67@example.com",
      posted: "last year",
      images: [
        "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 68,
      title: "Suburban Family Estate",
      type: "sale",
      price: 1250000,
      sqft: 3800,
      bedrooms: 5,
      bathrooms: 4,
      propertyType: "estate",
      condition: "excellent",
      description:
        "Grand family estate with pool, tennis court, and extensive grounds.",
      location: "654 Estate Rd, Atlanta, GA 30301",
      contactEmail: "owner68@example.com",
      posted: "this week",
      images: [
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 69,
      title: "Urban Rooftop Apartment",
      type: "rent",
      price: 2400,
      sqft: 1200,
      bedrooms: 2,
      bathrooms: 2,
      propertyType: "apartment",
      condition: "excellent",
      description:
        "Modern apartment with private rooftop terrace and city views.",
      location: "987 Rooftop Ave, Philadelphia, PA 19102",
      contactEmail: "owner69@example.com",
      posted: "last week",
      images: [
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
      ],
    },
    {
      id: 70,
      title: "Mountain Modern Home",
      type: "sale",
      price: 950000,
      sqft: 2400,
      bedrooms: 4,
      bathrooms: 3,
      propertyType: "house",
      condition: "excellent",
      description:
        "Contemporary mountain home with floor-to-ceiling windows and modern design.",
      location: "123 Alpine Way, Salt Lake City, UT 84101",
      contactEmail: "owner70@example.com",
      posted: "last month",
      images: [
        "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=2071&auto=format&fit=crop",
      ],
    },
  ],
};

export const communityData = {
  events: [
    {
      id: 201,
      title: "Community Garden Day",
      location: "Asheville, NC",
      date: "2025-10-05",
      description: "Help plant and maintain our local community garden.",
      images: ["garden_day_1.jpg", "garden_day_2.jpg"],
    },
    {
      id: 202,
      title: "Book Swap Event",
      location: "Winston-Salem, NC",
      date: "2025-09-30",
      description: "Bring your old books and swap them with others.",
      images: ["book_swap_1.jpg", "book_swap_2.jpg"],
    },
    {
      id: 203,
      title: "Neighborhood Cleanup",
      location: "Fayetteville, NC",
      date: "2025-10-02",
      description: "Join us to clean up our streets and parks.",
      images: ["cleanup_1.jpg", "cleanup_2.jpg"],
    },
    {
      id: 204,
      title: "Art Workshop for Kids",
      location: "Wilmington, NC",
      date: "2025-09-27",
      description: "Free art session for children aged 5-12.",
      images: ["art_workshop_1.jpg", "art_workshop_2.jpg"],
    },
    {
      id: 205,
      title: "Senior Citizen Dance",
      location: "Greensboro, NC",
      date: "2025-10-03",
      description: "A fun dance event for seniors and their families.",
      images: ["dance_1.jpg", "dance_2.jpg"],
    },
    {
      id: 206,
      title: "Pet Adoption Fair",
      location: "Charlotte, NC",
      date: "2025-09-29",
      description: "Come adopt a pet or volunteer at the fair.",
      images: ["pet_fair_1.jpg", "pet_fair_2.jpg"],
    },
    {
      id: 207,
      title: "Local Music Jam",
      location: "Raleigh, NC",
      date: "2025-10-04",
      description: "Bring your instrument and join the jam session.",
      images: ["music_jam_1.jpg", "music_jam_2.jpg"],
    },
    {
      id: 208,
      title: "Craft Fair",
      location: "Durham, NC",
      date: "2025-09-26",
      description: "Browse and buy handmade crafts from local artists.",
      images: ["craft_fair_1.jpg", "craft_fair_2.jpg"],
    },
    {
      id: 209,
      title: "History Walk",
      location: "Chapel Hill, NC",
      date: "2025-10-01",
      description: "Guided tour of local historical sites.",
      images: ["history_walk_1.jpg", "history_walk_2.jpg"],
    },
    {
      id: 210,
      title: "Food Truck Festival",
      location: "Asheville, NC",
      date: "2025-09-28",
      description: "Enjoy a variety of food trucks and live music.",
      images: ["food_fest_1.jpg", "food_fest_2.jpg"],
    },
    {
      id: 211,
      title: "Charity Run",
      location: "Winston-Salem, NC",
      date: "2025-10-06",
      description: "Participate in a 5K run to support local charities.",
      images: ["charity_run_1.jpg", "charity_run_2.jpg"],
    },
    {
      id: 212,
      title: "Movie Night Outdoors",
      location: "Fayetteville, NC",
      date: "2025-09-25",
      description: "Watch a family-friendly movie under the stars.",
      images: ["movie_night_1.jpg", "movie_night_2.jpg"],
    },
    {
      id: 213,
      title: "Cooking Class",
      location: "Wilmington, NC",
      date: "2025-10-02",
      description: "Learn to cook a healthy meal with a local chef.",
      images: ["cooking_class_1.jpg", "cooking_class_2.jpg"],
    },
    {
      id: 214,
      title: "Bike Ride for Charity",
      location: "Greensboro, NC",
      date: "2025-09-30",
      description: "Join a 10-mile bike ride to raise funds.",
      images: ["bike_ride_1.jpg", "bike_ride_2.jpg"],
    },
    {
      id: 215,
      title: "Photography Walk",
      location: "Charlotte, NC",
      date: "2025-10-05",
      description: "Explore and capture the beauty of the city.",
      images: ["photo_walk_1.jpg", "photo_walk_2.jpg"],
    },
    {
      id: 216,
      title: "Trivia Night",
      location: "Raleigh, NC",
      date: "2025-09-27",
      description: "Test your knowledge at our community trivia night.",
      images: ["trivia_night_1.jpg", "trivia_night_2.jpg"],
    },
    {
      id: 217,
      title: "Gardening Tips Workshop",
      location: "Durham, NC",
      date: "2025-10-03",
      description: "Learn gardening tips from local experts.",
      images: ["garden_tips_1.jpg", "garden_tips_2.jpg"],
    },
    {
      id: 218,
      title: "Pottery Class",
      location: "Chapel Hill, NC",
      date: "2025-09-29",
      description: "Create your own pottery piece in this class.",
      images: ["pottery_class_1.jpg", "pottery_class_2.jpg"],
    },
    {
      id: 219,
      title: "Community Picnic",
      location: "Asheville, NC",
      date: "2025-10-01",
      description: "Bring a dish and enjoy a day in the park.",
      images: ["picnic_1.jpg", "picnic_2.jpg"],
    },
    {
      id: 220,
      title: "Storytelling Hour",
      location: "Winston-Salem, NC",
      date: "2025-09-26",
      description: "Listen to local storytellers share their tales.",
      images: ["story_hour_1.jpg", "story_hour_2.jpg"],
    },
    {
      id: 221,
      title: "Fitness Bootcamp",
      location: "Fayetteville, NC",
      date: "2025-10-04",
      description: "Join a free outdoor fitness bootcamp.",
      images: ["bootcamp_1.jpg", "bootcamp_2.jpg"],
    },
    {
      id: 222,
      title: "Craft Beer Tasting",
      location: "Wilmington, NC",
      date: "2025-09-28",
      description: "Sample local craft beers and meet brewers.",
      images: ["beer_tasting_1.jpg", "beer_tasting_2.jpg"],
    },
    {
      id: 223,
      title: "Kids’ Science Fair",
      location: "Greensboro, NC",
      date: "2025-10-02",
      description: "Fun science experiments for kids and families.",
      images: ["science_fair_1.jpg", "science_fair_2.jpg"],
    },
    {
      id: 224,
      title: "Farmers Market Day",
      location: "Charlotte, NC",
      date: "2025-09-30",
      description: "Shop fresh produce and handmade goods.",
      images: ["farmers_market_1.jpg", "farmers_market_2.jpg"],
    },
    {
      id: 225,
      title: "Dance Lessons",
      location: "Raleigh, NC",
      date: "2025-10-06",
      description: "Learn ballroom dancing with a local instructor.",
      images: ["dance_lesson_1.jpg", "dance_lesson_2.jpg"],
    },
    {
      id: 226,
      title: "Bird Watching Walk",
      location: "Durham, NC",
      date: "2025-09-27",
      description: "Explore local trails and spot native birds.",
      images: ["bird_walk_1.jpg", "bird_walk_2.jpg"],
    },
    {
      id: 227,
      title: "DIY Home Repair Workshop",
      location: "Chapel Hill, NC",
      date: "2025-10-03",
      description: "Learn basic home repair skills.",
      images: ["diy_repair_1.jpg", "diy_repair_2.jpg"],
    },
    {
      id: 228,
      title: "Poetry Reading",
      location: "Asheville, NC",
      date: "2025-09-29",
      description: "Listen to local poets share their work.",
      images: ["poetry_reading_1.jpg", "poetry_reading_2.jpg"],
    },
    {
      id: 229,
      title: "Car Wash Fundraiser",
      location: "Winston-Salem, NC",
      date: "2025-10-01",
      description: "Support our community with a car wash fundraiser.",
      images: ["car_wash_1.jpg", "car_wash_2.jpg"],
    },
    {
      id: 230,
      title: "Board Game Night",
      location: "Fayetteville, NC",
      date: "2025-09-25",
      description: "Play board games with friends and neighbors.",
      images: ["game_night_1.jpg", "game_night_2.jpg"],
    },
    {
      id: 231,
      title: "Knitting Circle",
      location: "Wilmington, NC",
      date: "2025-10-02",
      description: "Join a group to knit and socialize.",
      images: ["knitting_circle_1.jpg", "knitting_circle_2.jpg"],
    },
    {
      id: 232,
      title: "Hiking Club Meetup",
      location: "Greensboro, NC",
      date: "2025-09-28",
      description: "Explore local trails with our hiking club.",
      images: ["hiking_meetup_1.jpg", "hiking_meetup_2.jpg"],
    },
    {
      id: 233,
      title: "Charity Bake Sale",
      location: "Charlotte, NC",
      date: "2025-10-05",
      description: "Buy homemade treats to support a good cause.",
      images: ["bake_sale_1.jpg", "bake_sale_2.jpg"],
    },
    {
      id: 234,
      title: "Language Exchange",
      location: "Raleigh, NC",
      date: "2025-09-26",
      description: "Practice a new language with native speakers.",
      images: ["language_exchange_1.jpg", "language_exchange_2.jpg"],
    },
    {
      id: 235,
      title: "Gardening Club Meeting",
      location: "Durham, NC",
      date: "2025-10-04",
      description: "Discuss gardening techniques and share plants.",
      images: ["garden_club_1.jpg", "garden_club_2.jpg"],
    },
    {
      id: 236,
      title: "Street Art Tour",
      location: "Chapel Hill, NC",
      date: "2025-09-30",
      description: "Discover local street art with a guided tour.",
      images: ["art_tour_1.jpg", "art_tour_2.jpg"],
    },
    {
      id: 237,
      title: "Volunteer Training",
      location: "Asheville, NC",
      date: "2025-10-03",
      description: "Training session for new community volunteers.",
      images: ["volunteer_training_1.jpg", "volunteer_training_2.jpg"],
    },
    {
      id: 238,
      title: "Craft Beer Festival",
      location: "Winston-Salem, NC",
      date: "2025-09-27",
      description: "Celebrate local breweries with a festival.",
      images: ["beer_fest_1.jpg", "beer_fest_2.jpg"],
    },
    {
      id: 239,
      title: "Kids’ Soccer Clinic",
      location: "Fayetteville, NC",
      date: "2025-10-01",
      description: "Free soccer clinic for kids aged 6-12.",
      images: ["soccer_clinic_1.jpg", "soccer_clinic_2.jpg"],
    },
    {
      id: 240,
      title: "History Lecture",
      location: "Wilmington, NC",
      date: "2025-09-29",
      description: "Learn about local history from an expert.",
      images: ["history_lecture_1.jpg", "history_lecture_2.jpg"],
    },
    {
      id: 241,
      title: "Community Choir Practice",
      location: "Greensboro, NC",
      date: "2025-10-06",
      description: "Join our community choir for practice.",
      images: ["choir_practice_1.jpg", "choir_practice_2.jpg"],
    },
    {
      id: 242,
      title: "Painting Class",
      location: "Charlotte, NC",
      date: "2025-09-28",
      description: "Learn painting techniques with a local artist.",
      images: ["painting_class_1.jpg", "painting_class_2.jpg"],
    },
    {
      id: 243,
      title: "Tree Planting Day",
      location: "Raleigh, NC",
      date: "2025-10-02",
      description: "Help plant trees to green our community.",
      images: ["tree_planting_1.jpg", "tree_planting_2.jpg"],
    },
    {
      id: 244,
      title: "Tech Help Desk",
      location: "Durham, NC",
      date: "2025-09-25",
      description: "Get free tech support from local experts.",
      images: ["tech_help_1.jpg", "tech_help_2.jpg"],
    },
    {
      id: 245,
      title: "Dance Performance",
      location: "Chapel Hill, NC",
      date: "2025-10-05",
      description: "Enjoy a free dance performance by local dancers.",
      images: ["dance_perf_1.jpg", "dance_perf_2.jpg"],
    },
    {
      id: 246,
      title: "Cooking Competition",
      location: "Asheville, NC",
      date: "2025-09-30",
      description: "Watch or join a community cooking contest.",
      images: ["cooking_comp_1.jpg", "cooking_comp_2.jpg"],
    },
    {
      id: 247,
      title: "Nature Photography",
      location: "Winston-Salem, NC",
      date: "2025-10-03",
      description: "Capture nature with a guided photography session.",
      images: ["nature_photo_1.jpg", "nature_photo_2.jpg"],
    },
    {
      id: 248,
      title: "Community Forum",
      location: "Fayetteville, NC",
      date: "2025-09-26",
      description: "Discuss local issues at our open forum.",
      images: ["forum_1.jpg", "forum_2.jpg"],
    },
    {
      id: 249,
      title: "Sewing Workshop",
      location: "Wilmington, NC",
      date: "2025-10-04",
      description: "Learn basic sewing skills in this workshop.",
      images: ["sewing_workshop_1.jpg", "sewing_workshop_2.jpg"],
    },
    {
      id: 250,
      title: "Holiday Planning Meeting",
      location: "Greensboro, NC",
      date: "2025-09-27",
      description: "Plan community holiday events together.",
      images: ["holiday_meeting_1.jpg", "holiday_meeting_2.jpg"],
    },
  ],
};
